// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.translatecore

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_translatecore_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_translatecore_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "translatecore"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceTranslationSinkMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`text`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("uniffiFree", "uniffiClone", "onPartial")
internal open class UniffiVTableCallbackInterfaceTranslationSink(
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    @JvmField internal var `uniffiClone`: UniffiCallbackInterfaceClone? = null,
    @JvmField internal var `onPartial`: UniffiCallbackInterfaceTranslationSinkMethod0? = null,
) : Structure() {
    class UniffiByValue(
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
        `uniffiClone`: UniffiCallbackInterfaceClone? = null,
        `onPartial`: UniffiCallbackInterfaceTranslationSinkMethod0? = null,
    ): UniffiVTableCallbackInterfaceTranslationSink(`uniffiFree`,`uniffiClone`,`onPartial`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceTranslationSink) {
        `uniffiFree` = other.`uniffiFree`
        `uniffiClone` = other.`uniffiClone`
        `onPartial` = other.`onPartial`
    }

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "translatecore"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }

    internal fun ensureInitialized() = Unit
    external fun uniffi_translatecore_checksum_func_asr_load(
    ): Int
    external fun uniffi_translatecore_checksum_func_asr_recognize(
    ): Int
    external fun uniffi_translatecore_checksum_func_asr_stream_accept(
    ): Int
    external fun uniffi_translatecore_checksum_func_asr_stream_load(
    ): Int
    external fun uniffi_translatecore_checksum_func_asr_stream_reset(
    ): Int
    external fun uniffi_translatecore_checksum_func_core_version(
    ): Int
    external fun uniffi_translatecore_checksum_func_greeting(
    ): Int
    external fun uniffi_translatecore_checksum_func_sherpa_version(
    ): Int
    external fun uniffi_translatecore_checksum_func_translate_load(
    ): Int
    external fun uniffi_translatecore_checksum_func_translate_smoke(
    ): Int
    external fun uniffi_translatecore_checksum_func_translate_text(
    ): Int
    external fun uniffi_translatecore_checksum_func_translate_text_streaming(
    ): Int
    external fun uniffi_translatecore_checksum_func_vad_accept(
    ): Int
    external fun uniffi_translatecore_checksum_func_vad_flush(
    ): Int
    external fun uniffi_translatecore_checksum_func_vad_load(
    ): Int
    external fun uniffi_translatecore_checksum_func_vad_reset(
    ): Int
    external fun uniffi_translatecore_checksum_method_translationsink_on_partial(
    ): Int
    external fun ffi_translatecore_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "translatecore"))
        uniffiCallbackInterfaceTranslationSink.register(this)
        
    }

    internal fun ensureInitialized() = Unit
    external fun uniffi_translatecore_fn_init_callback_vtable_translationsink(`vtable`: UniffiVTableCallbackInterfaceTranslationSink,
    ): Unit
    external fun uniffi_translatecore_fn_func_asr_load(`modelDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_translatecore_fn_func_asr_recognize(`modelDir`: RustBuffer.ByValue,`pcm16le`: RustBuffer.ByValue,`sampleRate`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_asr_stream_accept(`modelDir`: RustBuffer.ByValue,`pcm16le`: RustBuffer.ByValue,`sampleRate`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_asr_stream_load(`modelDir`: RustBuffer.ByValue,`rule1`: Float,`rule2`: Float,`rule3`: Float,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_translatecore_fn_func_asr_stream_reset(`modelDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_translatecore_fn_func_core_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_greeting(`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_sherpa_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_translate_load(`modelDir`: RustBuffer.ByValue,`ortDylib`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_translatecore_fn_func_translate_smoke(`ortDylib`: RustBuffer.ByValue,`modelPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_translate_text(`modelDir`: RustBuffer.ByValue,`text`: RustBuffer.ByValue,`srcLang`: RustBuffer.ByValue,`tgtLang`: RustBuffer.ByValue,`ortDylib`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_translate_text_streaming(`modelDir`: RustBuffer.ByValue,`text`: RustBuffer.ByValue,`srcLang`: RustBuffer.ByValue,`tgtLang`: RustBuffer.ByValue,`ortDylib`: RustBuffer.ByValue,`sink`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_vad_accept(`modelDir`: RustBuffer.ByValue,`pcm16le`: RustBuffer.ByValue,`sampleRate`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_vad_flush(`modelDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_translatecore_fn_func_vad_load(`modelDir`: RustBuffer.ByValue,`threshold`: Float,`minSilenceS`: Float,`minSpeechS`: Float,`maxSpeechS`: Float,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_translatecore_fn_func_vad_reset(`modelDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_translatecore_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_translatecore_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_translatecore_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_translatecore_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_translatecore_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_translatecore_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_translatecore_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_translatecore_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_translatecore_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_translatecore_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_translatecore_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_translatecore_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_translatecore_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_translatecore_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_translatecore_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_translatecore_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_translatecore_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_translatecore_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if ((lib.uniffi_translatecore_checksum_func_asr_load() and 0xFFFF) != 21069) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_asr_recognize() and 0xFFFF) != 38824) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_asr_stream_accept() and 0xFFFF) != 25770) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_asr_stream_load() and 0xFFFF) != 1011) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_asr_stream_reset() and 0xFFFF) != 31695) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_core_version() and 0xFFFF) != 25502) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_greeting() and 0xFFFF) != 47274) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_sherpa_version() and 0xFFFF) != 53038) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_translate_load() and 0xFFFF) != 7735) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_translate_smoke() and 0xFFFF) != 55417) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_translate_text() and 0xFFFF) != 28256) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_translate_text_streaming() and 0xFFFF) != 29506) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_vad_accept() and 0xFFFF) != 40090) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_vad_flush() and 0xFFFF) != 39812) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_vad_load() and 0xFFFF) != 44808) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_func_vad_reset() and 0xFFFF) != 39461) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_translatecore_checksum_method_translationsink_on_partial() and 0xFFFF) != 46971) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    // Call arbitrary methods on IntegrityCheckingUniffiLib and UniffiLib to ensure that
    // their init blocks run. This ensures initialization across crates works as expected.
    IntegrityCheckingUniffiLib.ensureInitialized()
    UniffiLib.ensureInitialized()
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * Transcript plus SenseVoice's detected language tag (`<|en|>`, `<|ja|>`, ...;
 * empty if the model didn't report one). The tag drives translation direction.
 */
data class AsrResult (
    var `text`: kotlin.String
    , 
    var `lang`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAsrResult: FfiConverterRustBuffer<AsrResult> {
    override fun read(buf: ByteBuffer): AsrResult {
        return AsrResult(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: AsrResult) = (
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterString.allocationSize(value.`lang`)
    )

    override fun write(value: AsrResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`text`, buf)
            FfiConverterString.write(value.`lang`, buf)
    }
}



/**
 * Partial transcript from the streaming recognizer plus whether sherpa detected
 * an end-of-utterance on this chunk. On `endpoint`, `text` is the finalized
 * transcript for the segment that just ended and the stream has been reset.
 */
data class AsrStreamResult (
    var `text`: kotlin.String
    , 
    var `endpoint`: kotlin.Boolean
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAsrStreamResult: FfiConverterRustBuffer<AsrStreamResult> {
    override fun read(buf: ByteBuffer): AsrStreamResult {
        return AsrStreamResult(
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: AsrStreamResult) = (
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterBoolean.allocationSize(value.`endpoint`)
    )

    override fun write(value: AsrStreamResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`text`, buf)
            FfiConverterBoolean.write(value.`endpoint`, buf)
    }
}





sealed class AsrException: kotlin.Exception() {
    
    class Failed(
        
        val v1: kotlin.String
        ) : AsrException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<AsrException> {
        override fun lift(error_buf: RustBuffer.ByValue): AsrException = FfiConverterTypeAsrError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeAsrError : FfiConverterRustBuffer<AsrException> {
    override fun read(buf: ByteBuffer): AsrException {
        

        return when(buf.getInt()) {
            1 -> AsrException.Failed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: AsrException): ULong {
        return when(value) {
            is AsrException.Failed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: AsrException, buf: ByteBuffer) {
        when(value) {
            is AsrException.Failed -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class TranslateException: kotlin.Exception() {
    
    class Failed(
        
        val v1: kotlin.String
        ) : TranslateException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<TranslateException> {
        override fun lift(error_buf: RustBuffer.ByValue): TranslateException = FfiConverterTypeTranslateError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeTranslateError : FfiConverterRustBuffer<TranslateException> {
    override fun read(buf: ByteBuffer): TranslateException {
        

        return when(buf.getInt()) {
            1 -> TranslateException.Failed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: TranslateException): ULong {
        return when(value) {
            is TranslateException.Failed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: TranslateException, buf: ByteBuffer) {
        when(value) {
            is TranslateException.Failed -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class VadException: kotlin.Exception() {
    
    class Failed(
        
        val v1: kotlin.String
        ) : VadException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<VadException> {
        override fun lift(error_buf: RustBuffer.ByValue): VadException = FfiConverterTypeVadError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeVadError : FfiConverterRustBuffer<VadException> {
    override fun read(buf: ByteBuffer): VadException {
        

        return when(buf.getInt()) {
            1 -> VadException.Failed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: VadException): ULong {
        return when(value) {
            is VadException.Failed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: VadException, buf: ByteBuffer) {
        when(value) {
            is VadException.Failed -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





/**
 * Receives the partial translation as it is generated, one call per decoded
 * token with the text decoded so far. Implemented on the foreign (Kotlin) side.
 */
public interface TranslationSink {
    
    fun `onPartial`(`text`: kotlin.String)
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceTranslationSink {
    internal object `onPartial`: UniffiCallbackInterfaceTranslationSinkMethod0 {
        override fun callback(`uniffiHandle`: Long,`text`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeTranslationSink.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onPartial`(
                    FfiConverterString.lift(`text`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeTranslationSink.handleMap.remove(handle)
        }
    }

    internal object uniffiClone: UniffiCallbackInterfaceClone {
        override fun callback(handle: Long): Long {
            return FfiConverterTypeTranslationSink.handleMap.clone(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceTranslationSink.UniffiByValue(
        uniffiFree,
        uniffiClone,
        `onPartial`,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_translatecore_fn_init_callback_vtable_translationsink(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeTranslationSink: FfiConverterCallbackInterface<TranslationSink>()




/**
 * @suppress
 */
public object FfiConverterSequenceByteArray: FfiConverterRustBuffer<List<kotlin.ByteArray>> {
    override fun read(buf: ByteBuffer): List<kotlin.ByteArray> {
        val len = buf.getInt()
        return List<kotlin.ByteArray>(len) {
            FfiConverterByteArray.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.ByteArray>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterByteArray.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.ByteArray>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterByteArray.write(it, buf)
        }
    }
}
        /**
         * Loads the SenseVoice recognizer under `model_dir` into the resident engine
         * without recognizing anything, to warm it up. Idempotent per `model_dir`.
         */
    @Throws(AsrException::class) fun `asrLoad`(`modelDir`: kotlin.String)
        = 
    uniffiRustCallWithError(AsrException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_asr_load(
    
        
        FfiConverterString.lower(`modelDir`),_status)
}
    
    

        /**
         * Transcribes 16 kHz mono PCM (signed 16-bit little-endian) with the SenseVoice
         * model under `model_dir`. Language is auto-detected. Returns the transcript.
         * Bytes are used over the FFI to avoid boxing tens of thousands of floats.
         * Loads the recognizer on first use, then reuses the resident engine.
         */
    @Throws(AsrException::class) fun `asrRecognize`(`modelDir`: kotlin.String, `pcm16le`: kotlin.ByteArray, `sampleRate`: kotlin.Int): AsrResult {
            return FfiConverterTypeAsrResult.lift(
    uniffiRustCallWithError(AsrException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_asr_recognize(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterByteArray.lower(`pcm16le`),
        FfiConverterInt.lower(`sampleRate`),_status)
}
    )
    }
    

        /**
         * Feeds one chunk of 16 kHz mono PCM (signed 16-bit little-endian) into the
         * resident streaming recognizer and returns the current partial transcript and
         * whether an utterance just ended. Loads the recognizer on first use.
         */
    @Throws(AsrException::class) fun `asrStreamAccept`(`modelDir`: kotlin.String, `pcm16le`: kotlin.ByteArray, `sampleRate`: kotlin.Int): AsrStreamResult {
            return FfiConverterTypeAsrStreamResult.lift(
    uniffiRustCallWithError(AsrException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_asr_stream_accept(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterByteArray.lower(`pcm16le`),
        FfiConverterInt.lower(`sampleRate`),_status)
}
    )
    }
    

        /**
         * Loads the streaming (nemotron-en) recognizer under `model_dir` and creates its
         * resident stream. `rule1`/`rule2`/`rule3` are the endpoint rules in seconds
         * (trailing silence before / after decoded speech, and max utterance length);
         * the recognizer is recreated when they change. Idempotent for equal arguments.
         */
    @Throws(AsrException::class) fun `asrStreamLoad`(`modelDir`: kotlin.String, `rule1`: kotlin.Float, `rule2`: kotlin.Float, `rule3`: kotlin.Float)
        = 
    uniffiRustCallWithError(AsrException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_asr_stream_load(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterFloat.lower(`rule1`),
        FfiConverterFloat.lower(`rule2`),
        FfiConverterFloat.lower(`rule3`),_status)
}
    
    

        /**
         * Discards any in-progress utterance in the resident stream (e.g. when the user
         * stops recording).
         */
    @Throws(AsrException::class) fun `asrStreamReset`(`modelDir`: kotlin.String)
        = 
    uniffiRustCallWithError(AsrException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_asr_stream_reset(
    
        
        FfiConverterString.lower(`modelDir`),_status)
}
    
    

        /**
         * Version banner for the native core. Used by the PoC to confirm the app is
         * actually executing Rust rather than a Kotlin stub.
         */ fun `coreVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_translatecore_fn_func_core_version(
    
        _status)
}
    )
    }
    

        /**
         * Echoes a greeting from the native side, proving arguments cross the FFI boundary.
         */ fun `greeting`(`name`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_translatecore_fn_func_greeting(
    
        
        FfiConverterString.lower(`name`),_status)
}
    )
    }
    

        /**
         * Reports the linked sherpa-onnx version. Calling this proves the heavy native
         * stack (sherpa-onnx + onnxruntime) actually loads and executes on the device,
         * without needing any model yet.
         */ fun `sherpaVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_translatecore_fn_func_sherpa_version(
    
        _status)
}
    )
    }
    

        /**
         * Loads the NLLB models under `model_dir` into the resident engine without
         * translating, so the UI can warm them up once and surface a "loaded" state.
         * Idempotent: a no-op when the same `model_dir` is already resident.
         */
    @Throws(TranslateException::class) fun `translateLoad`(`modelDir`: kotlin.String, `ortDylib`: kotlin.String)
        = 
    uniffiRustCallWithError(TranslateException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_translate_load(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterString.lower(`ortDylib`),_status)
}
    
    

        /**
         * Step A smoke: load onnxruntime via `ort` and open an ONNX model on device.
         */
    @Throws(TranslateException::class) fun `translateSmoke`(`ortDylib`: kotlin.String, `modelPath`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(TranslateException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_translate_smoke(
    
        
        FfiConverterString.lower(`ortDylib`),
        FfiConverterString.lower(`modelPath`),_status)
}
    )
    }
    

        /**
         * Translates `text` from `src_lang` to `tgt_lang` (NLLB FLORES codes, e.g.
         * "eng_Latn", "jpn_Jpan") using the NLLB ONNX models under `model_dir`. Loads
         * the models on first use, then reuses the resident engine.
         */
    @Throws(TranslateException::class) fun `translateText`(`modelDir`: kotlin.String, `text`: kotlin.String, `srcLang`: kotlin.String, `tgtLang`: kotlin.String, `ortDylib`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(TranslateException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_translate_text(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterString.lower(`text`),
        FfiConverterString.lower(`srcLang`),
        FfiConverterString.lower(`tgtLang`),
        FfiConverterString.lower(`ortDylib`),_status)
}
    )
    }
    

        /**
         * Streaming variant of [`translate_text`]: returns the final translation and, as
         * it decodes, pushes each growing partial to `sink` so the UI can render the
         * translation left-to-right. Callbacks arrive on the calling thread.
         */
    @Throws(TranslateException::class) fun `translateTextStreaming`(`modelDir`: kotlin.String, `text`: kotlin.String, `srcLang`: kotlin.String, `tgtLang`: kotlin.String, `ortDylib`: kotlin.String, `sink`: TranslationSink): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(TranslateException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_translate_text_streaming(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterString.lower(`text`),
        FfiConverterString.lower(`srcLang`),
        FfiConverterString.lower(`tgtLang`),
        FfiConverterString.lower(`ortDylib`),
        FfiConverterTypeTranslationSink.lower(`sink`),_status)
}
    )
    }
    

        /**
         * Feeds one chunk of 16 kHz mono PCM16 LE into the resident detector and returns
         * the speech segments that finished on this chunk (each as PCM16 LE, ready for
         * `asr_recognize`). Usually empty until a pause ends an utterance.
         */
    @Throws(VadException::class) fun `vadAccept`(`modelDir`: kotlin.String, `pcm16le`: kotlin.ByteArray, `sampleRate`: kotlin.Int): List<kotlin.ByteArray> {
            return FfiConverterSequenceByteArray.lift(
    uniffiRustCallWithError(VadException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_vad_accept(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterByteArray.lower(`pcm16le`),
        FfiConverterInt.lower(`sampleRate`),_status)
}
    )
    }
    

        /**
         * Forces the in-progress utterance to be emitted (e.g. when recording stops
         * mid-sentence). Returns the flushed segment(s) as PCM16 LE.
         */
    @Throws(VadException::class) fun `vadFlush`(`modelDir`: kotlin.String): List<kotlin.ByteArray> {
            return FfiConverterSequenceByteArray.lift(
    uniffiRustCallWithError(VadException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_vad_flush(
    
        
        FfiConverterString.lower(`modelDir`),_status)
}
    )
    }
    

        /**
         * Loads/configures the Silero VAD under `model_dir`. The tuning params (speech
         * probability `threshold`, and minimum silence / minimum speech / maximum speech
         * durations in seconds) are baked in at creation, so changing them recreates the
         * detector. Idempotent for equal arguments.
         */
    @Throws(VadException::class) fun `vadLoad`(`modelDir`: kotlin.String, `threshold`: kotlin.Float, `minSilenceS`: kotlin.Float, `minSpeechS`: kotlin.Float, `maxSpeechS`: kotlin.Float)
        = 
    uniffiRustCallWithError(VadException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_vad_load(
    
        
        FfiConverterString.lower(`modelDir`),
        FfiConverterFloat.lower(`threshold`),
        FfiConverterFloat.lower(`minSilenceS`),
        FfiConverterFloat.lower(`minSpeechS`),
        FfiConverterFloat.lower(`maxSpeechS`),_status)
}
    
    

        /**
         * Discards any buffered audio / in-progress utterance in the resident detector.
         */
    @Throws(VadException::class) fun `vadReset`(`modelDir`: kotlin.String)
        = 
    uniffiRustCallWithError(VadException) { _status ->
    UniffiLib.uniffi_translatecore_fn_func_vad_reset(
    
        
        FfiConverterString.lower(`modelDir`),_status)
}
    
    


